// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/billing/v1/billing.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BillingQueryService_GetInvoiceByOrder_FullMethodName = "/billing.v1.BillingQueryService/GetInvoiceByOrder"
	BillingQueryService_ListInvoices_FullMethodName      = "/billing.v1.BillingQueryService/ListInvoices"
	BillingQueryService_GetBillingStats_FullMethodName   = "/billing.v1.BillingQueryService/GetBillingStats"
)

// BillingQueryServiceClient is the client API for BillingQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillingQueryServiceClient interface {
	GetInvoiceByOrder(ctx context.Context, in *GetInvoiceByOrderRequest, opts ...grpc.CallOption) (*GetInvoiceResponse, error)
	ListInvoices(ctx context.Context, in *ListInvoicesRequest, opts ...grpc.CallOption) (*ListInvoicesResponse, error)
	GetBillingStats(ctx context.Context, in *GetBillingStatsRequest, opts ...grpc.CallOption) (*GetBillingStatsResponse, error)
}

type billingQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingQueryServiceClient(cc grpc.ClientConnInterface) BillingQueryServiceClient {
	return &billingQueryServiceClient{cc}
}

func (c *billingQueryServiceClient) GetInvoiceByOrder(ctx context.Context, in *GetInvoiceByOrderRequest, opts ...grpc.CallOption) (*GetInvoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInvoiceResponse)
	err := c.cc.Invoke(ctx, BillingQueryService_GetInvoiceByOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingQueryServiceClient) ListInvoices(ctx context.Context, in *ListInvoicesRequest, opts ...grpc.CallOption) (*ListInvoicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInvoicesResponse)
	err := c.cc.Invoke(ctx, BillingQueryService_ListInvoices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingQueryServiceClient) GetBillingStats(ctx context.Context, in *GetBillingStatsRequest, opts ...grpc.CallOption) (*GetBillingStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBillingStatsResponse)
	err := c.cc.Invoke(ctx, BillingQueryService_GetBillingStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingQueryServiceServer is the server API for BillingQueryService service.
// All implementations must embed UnimplementedBillingQueryServiceServer
// for forward compatibility.
type BillingQueryServiceServer interface {
	GetInvoiceByOrder(context.Context, *GetInvoiceByOrderRequest) (*GetInvoiceResponse, error)
	ListInvoices(context.Context, *ListInvoicesRequest) (*ListInvoicesResponse, error)
	GetBillingStats(context.Context, *GetBillingStatsRequest) (*GetBillingStatsResponse, error)
	mustEmbedUnimplementedBillingQueryServiceServer()
}

// UnimplementedBillingQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingQueryServiceServer struct{}

func (UnimplementedBillingQueryServiceServer) GetInvoiceByOrder(context.Context, *GetInvoiceByOrderRequest) (*GetInvoiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInvoiceByOrder not implemented")
}
func (UnimplementedBillingQueryServiceServer) ListInvoices(context.Context, *ListInvoicesRequest) (*ListInvoicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInvoices not implemented")
}
func (UnimplementedBillingQueryServiceServer) GetBillingStats(context.Context, *GetBillingStatsRequest) (*GetBillingStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBillingStats not implemented")
}
func (UnimplementedBillingQueryServiceServer) mustEmbedUnimplementedBillingQueryServiceServer() {}
func (UnimplementedBillingQueryServiceServer) testEmbeddedByValue()                             {}

// UnsafeBillingQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingQueryServiceServer will
// result in compilation errors.
type UnsafeBillingQueryServiceServer interface {
	mustEmbedUnimplementedBillingQueryServiceServer()
}

func RegisterBillingQueryServiceServer(s grpc.ServiceRegistrar, srv BillingQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedBillingQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillingQueryService_ServiceDesc, srv)
}

func _BillingQueryService_GetInvoiceByOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInvoiceByOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingQueryServiceServer).GetInvoiceByOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingQueryService_GetInvoiceByOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingQueryServiceServer).GetInvoiceByOrder(ctx, req.(*GetInvoiceByOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingQueryService_ListInvoices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInvoicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingQueryServiceServer).ListInvoices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingQueryService_ListInvoices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingQueryServiceServer).ListInvoices(ctx, req.(*ListInvoicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingQueryService_GetBillingStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBillingStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingQueryServiceServer).GetBillingStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingQueryService_GetBillingStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingQueryServiceServer).GetBillingStats(ctx, req.(*GetBillingStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingQueryService_ServiceDesc is the grpc.ServiceDesc for BillingQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing.v1.BillingQueryService",
	HandlerType: (*BillingQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInvoiceByOrder",
			Handler:    _BillingQueryService_GetInvoiceByOrder_Handler,
		},
		{
			MethodName: "ListInvoices",
			Handler:    _BillingQueryService_ListInvoices_Handler,
		},
		{
			MethodName: "GetBillingStats",
			Handler:    _BillingQueryService_GetBillingStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/billing/v1/billing.proto",
}
