// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/billing/v1/billing.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvoiceStatus int32

const (
	InvoiceStatus_INVOICE_STATUS_UNSPECIFIED InvoiceStatus = 0
	InvoiceStatus_INVOICE_STATUS_PENDING     InvoiceStatus = 1
	InvoiceStatus_INVOICE_STATUS_PAID        InvoiceStatus = 2
	InvoiceStatus_INVOICE_STATUS_CANCELLED   InvoiceStatus = 3
)

// Enum value maps for InvoiceStatus.
var (
	InvoiceStatus_name = map[int32]string{
		0: "INVOICE_STATUS_UNSPECIFIED",
		1: "INVOICE_STATUS_PENDING",
		2: "INVOICE_STATUS_PAID",
		3: "INVOICE_STATUS_CANCELLED",
	}
	InvoiceStatus_value = map[string]int32{
		"INVOICE_STATUS_UNSPECIFIED": 0,
		"INVOICE_STATUS_PENDING":     1,
		"INVOICE_STATUS_PAID":        2,
		"INVOICE_STATUS_CANCELLED":   3,
	}
)

func (x InvoiceStatus) Enum() *InvoiceStatus {
	p := new(InvoiceStatus)
	*p = x
	return p
}

func (x InvoiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvoiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_billing_v1_billing_proto_enumTypes[0].Descriptor()
}

func (InvoiceStatus) Type() protoreflect.EnumType {
	return &file_proto_billing_v1_billing_proto_enumTypes[0]
}

func (x InvoiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvoiceStatus.Descriptor instead.
func (InvoiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type Invoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        *Money                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        InvoiceStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=billing.v1.InvoiceStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PaidAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *Invoice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invoice) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Invoice) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Invoice) GetStatus() InvoiceStatus {
	if x != nil {
		return x.Status
	}
	return InvoiceStatus_INVOICE_STATUS_UNSPECIFIED
}

func (x *Invoice) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Invoice) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

type GetInvoiceByOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceByOrderRequest) Reset() {
	*x = GetInvoiceByOrderRequest{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceByOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceByOrderRequest) ProtoMessage() {}

func (x *GetInvoiceByOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceByOrderRequest.ProtoReflect.Descriptor instead.
func (*GetInvoiceByOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{2}
}

func (x *GetInvoiceByOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       *Invoice               `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceResponse) Reset() {
	*x = GetInvoiceResponse{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceResponse) ProtoMessage() {}

func (x *GetInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceResponse.ProtoReflect.Descriptor instead.
func (*GetInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *GetInvoiceResponse) GetInvoice() *Invoice {
	if x != nil {
		return x.Invoice
	}
	return nil
}

type ListInvoicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        InvoiceStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=billing.v1.InvoiceStatus" json:"status,omitempty"` // optional filter
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvoicesRequest) Reset() {
	*x = ListInvoicesRequest{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoicesRequest) ProtoMessage() {}

func (x *ListInvoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoicesRequest.ProtoReflect.Descriptor instead.
func (*ListInvoicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{4}
}

func (x *ListInvoicesRequest) GetStatus() InvoiceStatus {
	if x != nil {
		return x.Status
	}
	return InvoiceStatus_INVOICE_STATUS_UNSPECIFIED
}

func (x *ListInvoicesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListInvoicesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListInvoicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoices      []*Invoice             `protobuf:"bytes,1,rep,name=invoices,proto3" json:"invoices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvoicesResponse) Reset() {
	*x = ListInvoicesResponse{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoicesResponse) ProtoMessage() {}

func (x *ListInvoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoicesResponse.ProtoReflect.Descriptor instead.
func (*ListInvoicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{5}
}

func (x *ListInvoicesResponse) GetInvoices() []*Invoice {
	if x != nil {
		return x.Invoices
	}
	return nil
}

type GetBillingStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingStatsRequest) Reset() {
	*x = GetBillingStatsRequest{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingStatsRequest) ProtoMessage() {}

func (x *GetBillingStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingStatsRequest.ProtoReflect.Descriptor instead.
func (*GetBillingStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{6}
}

type GetBillingStatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalInvoices     int64                  `protobuf:"varint,1,opt,name=total_invoices,json=totalInvoices,proto3" json:"total_invoices,omitempty"`
	PaidInvoices      int64                  `protobuf:"varint,2,opt,name=paid_invoices,json=paidInvoices,proto3" json:"paid_invoices,omitempty"`
	PendingInvoices   int64                  `protobuf:"varint,3,opt,name=pending_invoices,json=pendingInvoices,proto3" json:"pending_invoices,omitempty"`
	CancelledInvoices int64                  `protobuf:"varint,4,opt,name=cancelled_invoices,json=cancelledInvoices,proto3" json:"cancelled_invoices,omitempty"`
	TotalRevenue      *Money                 `protobuf:"bytes,5,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetBillingStatsResponse) Reset() {
	*x = GetBillingStatsResponse{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingStatsResponse) ProtoMessage() {}

func (x *GetBillingStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingStatsResponse.ProtoReflect.Descriptor instead.
func (*GetBillingStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{7}
}

func (x *GetBillingStatsResponse) GetTotalInvoices() int64 {
	if x != nil {
		return x.TotalInvoices
	}
	return 0
}

func (x *GetBillingStatsResponse) GetPaidInvoices() int64 {
	if x != nil {
		return x.PaidInvoices
	}
	return 0
}

func (x *GetBillingStatsResponse) GetPendingInvoices() int64 {
	if x != nil {
		return x.PendingInvoices
	}
	return 0
}

func (x *GetBillingStatsResponse) GetCancelledInvoices() int64 {
	if x != nil {
		return x.CancelledInvoices
	}
	return 0
}

func (x *GetBillingStatsResponse) GetTotalRevenue() *Money {
	if x != nil {
		return x.TotalRevenue
	}
	return nil
}

var File_proto_billing_v1_billing_proto protoreflect.FileDescriptor

const file_proto_billing_v1_billing_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/billing/v1/billing.proto\x12\n" +
	"billing.v1\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\x05Money\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\x82\x02\n" +
	"\aInvoice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12)\n" +
	"\x06amount\x18\x03 \x01(\v2\x11.billing.v1.MoneyR\x06amount\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.billing.v1.InvoiceStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\apaid_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\"5\n" +
	"\x18GetInvoiceByOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"C\n" +
	"\x12GetInvoiceResponse\x12-\n" +
	"\ainvoice\x18\x01 \x01(\v2\x13.billing.v1.InvoiceR\ainvoice\"v\n" +
	"\x13ListInvoicesRequest\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.billing.v1.InvoiceStatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"G\n" +
	"\x14ListInvoicesResponse\x12/\n" +
	"\binvoices\x18\x01 \x03(\v2\x13.billing.v1.InvoiceR\binvoices\"\x18\n" +
	"\x16GetBillingStatsRequest\"\xf7\x01\n" +
	"\x17GetBillingStatsResponse\x12%\n" +
	"\x0etotal_invoices\x18\x01 \x01(\x03R\rtotalInvoices\x12#\n" +
	"\rpaid_invoices\x18\x02 \x01(\x03R\fpaidInvoices\x12)\n" +
	"\x10pending_invoices\x18\x03 \x01(\x03R\x0fpendingInvoices\x12-\n" +
	"\x12cancelled_invoices\x18\x04 \x01(\x03R\x11cancelledInvoices\x126\n" +
	"\rtotal_revenue\x18\x05 \x01(\v2\x11.billing.v1.MoneyR\ftotalRevenue*\x82\x01\n" +
	"\rInvoiceStatus\x12\x1e\n" +
	"\x1aINVOICE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16INVOICE_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13INVOICE_STATUS_PAID\x10\x02\x12\x1c\n" +
	"\x18INVOICE_STATUS_CANCELLED\x10\x032\x9f\x02\n" +
	"\x13BillingQueryService\x12Y\n" +
	"\x11GetInvoiceByOrder\x12$.billing.v1.GetInvoiceByOrderRequest\x1a\x1e.billing.v1.GetInvoiceResponse\x12Q\n" +
	"\fListInvoices\x12\x1f.billing.v1.ListInvoicesRequest\x1a .billing.v1.ListInvoicesResponse\x12Z\n" +
	"\x0fGetBillingStats\x12\".billing.v1.GetBillingStatsRequest\x1a#.billing.v1.GetBillingStatsResponseB;Z9order-billing-system/billing_service/internal/proto/pb;pbb\x06proto3"

var (
	file_proto_billing_v1_billing_proto_rawDescOnce sync.Once
	file_proto_billing_v1_billing_proto_rawDescData []byte
)

func file_proto_billing_v1_billing_proto_rawDescGZIP() []byte {
	file_proto_billing_v1_billing_proto_rawDescOnce.Do(func() {
		file_proto_billing_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_billing_v1_billing_proto_rawDesc), len(file_proto_billing_v1_billing_proto_rawDesc)))
	})
	return file_proto_billing_v1_billing_proto_rawDescData
}

var file_proto_billing_v1_billing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_billing_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_billing_v1_billing_proto_goTypes = []any{
	(InvoiceStatus)(0),               // 0: billing.v1.InvoiceStatus
	(*Money)(nil),                    // 1: billing.v1.Money
	(*Invoice)(nil),                  // 2: billing.v1.Invoice
	(*GetInvoiceByOrderRequest)(nil), // 3: billing.v1.GetInvoiceByOrderRequest
	(*GetInvoiceResponse)(nil),       // 4: billing.v1.GetInvoiceResponse
	(*ListInvoicesRequest)(nil),      // 5: billing.v1.ListInvoicesRequest
	(*ListInvoicesResponse)(nil),     // 6: billing.v1.ListInvoicesResponse
	(*GetBillingStatsRequest)(nil),   // 7: billing.v1.GetBillingStatsRequest
	(*GetBillingStatsResponse)(nil),  // 8: billing.v1.GetBillingStatsResponse
	(*timestamppb.Timestamp)(nil),    // 9: google.protobuf.Timestamp
}
var file_proto_billing_v1_billing_proto_depIdxs = []int32{
	1,  // 0: billing.v1.Invoice.amount:type_name -> billing.v1.Money
	0,  // 1: billing.v1.Invoice.status:type_name -> billing.v1.InvoiceStatus
	9,  // 2: billing.v1.Invoice.created_at:type_name -> google.protobuf.Timestamp
	9,  // 3: billing.v1.Invoice.paid_at:type_name -> google.protobuf.Timestamp
	2,  // 4: billing.v1.GetInvoiceResponse.invoice:type_name -> billing.v1.Invoice
	0,  // 5: billing.v1.ListInvoicesRequest.status:type_name -> billing.v1.InvoiceStatus
	2,  // 6: billing.v1.ListInvoicesResponse.invoices:type_name -> billing.v1.Invoice
	1,  // 7: billing.v1.GetBillingStatsResponse.total_revenue:type_name -> billing.v1.Money
	3,  // 8: billing.v1.BillingQueryService.GetInvoiceByOrder:input_type -> billing.v1.GetInvoiceByOrderRequest
	5,  // 9: billing.v1.BillingQueryService.ListInvoices:input_type -> billing.v1.ListInvoicesRequest
	7,  // 10: billing.v1.BillingQueryService.GetBillingStats:input_type -> billing.v1.GetBillingStatsRequest
	4,  // 11: billing.v1.BillingQueryService.GetInvoiceByOrder:output_type -> billing.v1.GetInvoiceResponse
	6,  // 12: billing.v1.BillingQueryService.ListInvoices:output_type -> billing.v1.ListInvoicesResponse
	8,  // 13: billing.v1.BillingQueryService.GetBillingStats:output_type -> billing.v1.GetBillingStatsResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_billing_v1_billing_proto_init() }
func file_proto_billing_v1_billing_proto_init() {
	if File_proto_billing_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_billing_v1_billing_proto_rawDesc), len(file_proto_billing_v1_billing_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_billing_v1_billing_proto_goTypes,
		DependencyIndexes: file_proto_billing_v1_billing_proto_depIdxs,
		EnumInfos:         file_proto_billing_v1_billing_proto_enumTypes,
		MessageInfos:      file_proto_billing_v1_billing_proto_msgTypes,
	}.Build()
	File_proto_billing_v1_billing_proto = out.File
	file_proto_billing_v1_billing_proto_goTypes = nil
	file_proto_billing_v1_billing_proto_depIdxs = nil
}
