name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  order-service:
    name: Order Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        working-directory: order_service
        run: go build ./...

      - name: Test
        working-directory: order_service
        run: go test ./... -v -cover

  billing-service:
    name: Billing Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        working-directory: billing_service
        run: go build ./...

      - name: Test
        working-directory: billing_service
        run: go test ./... -v -cover
